name: Create torrent

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'Direct Download Link'
        required: true
        default: ''
      file_name:
        description: 'Saved File Name (e.g. game.zip)'
        required: true
        default: 'downloaded_file.zip'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mktorrent aria2

      - name: Download File with Aria2
        run: |
          aria2c -x 16 -s 16 -o "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.download_url }}"

      - name: Create Torrent File
        run: |
          mktorrent -v -a "udp://tracker.opentrackr.org:1337/announce" "${{ github.event.inputs.file_name }}"

      - name: Upload Torrent Artifact
        uses: actions/upload-artifact@v4
        with:
          name: torrent-file
          path: "*.torrent"
